-- ===========================================
-- Multi-Tenant REST API Integration Service
-- Database Schema DDL Script for Oracle
-- ===========================================

-- ===========================================
-- CLIENT_CONFIGURATION Table
-- Stores client API endpoint configurations
-- ===========================================
CREATE TABLE CLIENT_CONFIGURATION (
    CLIENT_ID           VARCHAR2(50) PRIMARY KEY,
    CLIENT_NAME         VARCHAR2(200) NOT NULL,
    API_ENDPOINT_URL    VARCHAR2(500) NOT NULL,
    HTTP_METHOD         VARCHAR2(10) NOT NULL DEFAULT 'POST',
    API_KEY             VARCHAR2(1000),
    API_KEY_HEADER_NAME VARCHAR2(100) DEFAULT 'X-API-Key',
    TIMEOUT_SECONDS     NUMBER(10) DEFAULT 300,
    RETRY_ENABLED       NUMBER(1) DEFAULT 1,
    IS_ACTIVE           NUMBER(1) DEFAULT 1,
    CONTENT_TYPE        VARCHAR2(100) DEFAULT 'application/json',
    ADDITIONAL_HEADERS  CLOB,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(50) NOT NULL,
    UPDATED_AT          TIMESTAMP,
    UPDATED_BY          VARCHAR2(50),
    CONSTRAINT CHK_HTTP_METHOD CHECK (HTTP_METHOD IN ('GET', 'POST', 'PUT', 'DELETE', 'PATCH')),
    CONSTRAINT CHK_CLIENT_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT CHK_CLIENT_RETRY CHECK (RETRY_ENABLED IN (0, 1))
);

CREATE INDEX IDX_CLIENT_ACTIVE ON CLIENT_CONFIGURATION(IS_ACTIVE);
CREATE INDEX IDX_CLIENT_NAME ON CLIENT_CONFIGURATION(CLIENT_NAME);

COMMENT ON TABLE CLIENT_CONFIGURATION IS 'Stores configuration for each client API integration';
COMMENT ON COLUMN CLIENT_CONFIGURATION.CLIENT_ID IS 'Unique identifier for the client';
COMMENT ON COLUMN CLIENT_CONFIGURATION.API_KEY IS 'Encrypted API key for authentication';
COMMENT ON COLUMN CLIENT_CONFIGURATION.TIMEOUT_SECONDS IS 'Request timeout (default 5 minutes)';

-- ===========================================
-- CLIENT_EMAIL_RECIPIENTS Table
-- Stores email recipients for daily reports
-- ===========================================
CREATE TABLE CLIENT_EMAIL_RECIPIENTS (
    RECIPIENT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID       VARCHAR2(50) NOT NULL,
    EMAIL_ADDRESS   VARCHAR2(255) NOT NULL,
    RECIPIENT_NAME  VARCHAR2(200),
    RECIPIENT_TYPE  VARCHAR2(10) DEFAULT 'TO',
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50) NOT NULL,
    UPDATED_AT      TIMESTAMP,
    UPDATED_BY      VARCHAR2(50),
    CONSTRAINT FK_RECIPIENT_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT_CONFIGURATION(CLIENT_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_RECIPIENT_TYPE CHECK (RECIPIENT_TYPE IN ('TO', 'CC', 'BCC')),
    CONSTRAINT CHK_RECIPIENT_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE INDEX IDX_RECIPIENT_CLIENT ON CLIENT_EMAIL_RECIPIENTS(CLIENT_ID);
CREATE INDEX IDX_RECIPIENT_ACTIVE ON CLIENT_EMAIL_RECIPIENTS(IS_ACTIVE);

COMMENT ON TABLE CLIENT_EMAIL_RECIPIENTS IS 'Email recipients for daily audit reports';

-- ===========================================
-- FIELD_MAPPING Table
-- Stores field mapping configurations
-- ===========================================
CREATE TABLE FIELD_MAPPING (
    MAPPING_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID           VARCHAR2(50) NOT NULL,
    SOURCE_TABLE        VARCHAR2(100) NOT NULL,
    SOURCE_COLUMN       VARCHAR2(100) NOT NULL,
    TARGET_FIELD_PATH   VARCHAR2(500) NOT NULL,
    DATA_TYPE           VARCHAR2(20) DEFAULT 'STRING',
    TRANSFORMATION_RULE VARCHAR2(500),
    FIELD_NOTES         VARCHAR2(1000),
    IS_MANDATORY        NUMBER(1) DEFAULT 0,
    DEFAULT_VALUE       VARCHAR2(500),
    FIELD_ORDER         NUMBER(10) DEFAULT 0,
    IS_ACTIVE           NUMBER(1) DEFAULT 1,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(50) NOT NULL,
    UPDATED_AT          TIMESTAMP,
    UPDATED_BY          VARCHAR2(50),
    CONSTRAINT FK_MAPPING_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT_CONFIGURATION(CLIENT_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_DATA_TYPE CHECK (DATA_TYPE IN ('STRING', 'INTEGER', 'LONG', 'DECIMAL', 'DOUBLE', 'BOOLEAN', 'DATE', 'DATETIME', 'TIMESTAMP', 'ARRAY', 'OBJECT')),
    CONSTRAINT CHK_MAPPING_MANDATORY CHECK (IS_MANDATORY IN (0, 1)),
    CONSTRAINT CHK_MAPPING_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE INDEX IDX_MAPPING_CLIENT ON FIELD_MAPPING(CLIENT_ID);
CREATE INDEX IDX_MAPPING_TABLE ON FIELD_MAPPING(SOURCE_TABLE);
CREATE INDEX IDX_MAPPING_ACTIVE ON FIELD_MAPPING(IS_ACTIVE);
CREATE INDEX IDX_MAPPING_ORDER ON FIELD_MAPPING(FIELD_ORDER);

COMMENT ON TABLE FIELD_MAPPING IS 'Maps source database fields to target API payload fields';
COMMENT ON COLUMN FIELD_MAPPING.TARGET_FIELD_PATH IS 'JSON path notation e.g., customer.address.city';
COMMENT ON COLUMN FIELD_MAPPING.TRANSFORMATION_RULE IS 'Transformation rule e.g., DATE:yyyy-MM-dd, CONCAT:field1|field2';

-- ===========================================
-- AUDIT_LOG Table
-- Stores complete audit trail of API calls
-- ===========================================
CREATE TABLE AUDIT_LOG (
    AUDIT_ID            VARCHAR2(50) PRIMARY KEY,
    CLIENT_ID           VARCHAR2(50) NOT NULL,
    REQUEST_TIMESTAMP   TIMESTAMP NOT NULL,
    REQUEST_PAYLOAD     CLOB,
    REQUEST_HEADERS     CLOB,
    RESPONSE_TIMESTAMP  TIMESTAMP,
    RESPONSE_PAYLOAD    CLOB,
    RESPONSE_STATUS_CODE NUMBER(3),
    RESPONSE_HEADERS    CLOB,
    API_ENDPOINT_URL    VARCHAR2(500),
    HTTP_METHOD         VARCHAR2(10),
    EXECUTION_TIME_MS   NUMBER(20),
    SUCCESS_FLAG        NUMBER(1),
    ERROR_MESSAGE       CLOB,
    SOURCE_RECORD_ID    VARCHAR2(100),
    CORRELATION_ID      VARCHAR2(50),
    CREATED_BY          VARCHAR2(50),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_AUDIT_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT_CONFIGURATION(CLIENT_ID),
    CONSTRAINT CHK_AUDIT_SUCCESS CHECK (SUCCESS_FLAG IN (0, 1))
);

CREATE INDEX IDX_AUDIT_CLIENT ON AUDIT_LOG(CLIENT_ID);
CREATE INDEX IDX_AUDIT_REQUEST_TIME ON AUDIT_LOG(REQUEST_TIMESTAMP);
CREATE INDEX IDX_AUDIT_CORRELATION ON AUDIT_LOG(CORRELATION_ID);
CREATE INDEX IDX_AUDIT_SUCCESS ON AUDIT_LOG(SUCCESS_FLAG);
CREATE INDEX IDX_AUDIT_SOURCE_RECORD ON AUDIT_LOG(SOURCE_RECORD_ID);

-- Composite index for time-range queries by client
CREATE INDEX IDX_AUDIT_CLIENT_TIME ON AUDIT_LOG(CLIENT_ID, REQUEST_TIMESTAMP);

COMMENT ON TABLE AUDIT_LOG IS 'Complete audit trail of all API calls for compliance';
COMMENT ON COLUMN AUDIT_LOG.AUDIT_ID IS 'UUID for the audit record';
COMMENT ON COLUMN AUDIT_LOG.CORRELATION_ID IS 'Correlation ID for request tracking across systems';

-- ===========================================
-- FAILED_API_CALLS Table
-- Stores failed calls for retry mechanism
-- ===========================================
CREATE TABLE FAILED_API_CALLS (
    CALL_ID             VARCHAR2(50) PRIMARY KEY,
    CLIENT_ID           VARCHAR2(50) NOT NULL,
    REQUEST_PAYLOAD     CLOB NOT NULL,
    REQUEST_HEADERS     CLOB,
    API_ENDPOINT_URL    VARCHAR2(500) NOT NULL,
    HTTP_METHOD         VARCHAR2(10) NOT NULL,
    FAILURE_TIMESTAMP   TIMESTAMP NOT NULL,
    RETRY_COUNT         NUMBER(10) DEFAULT 0,
    MAX_RETRY_ATTEMPTS  NUMBER(10) DEFAULT 360,
    NEXT_RETRY_TIME     TIMESTAMP,
    ERROR_MESSAGE       CLOB,
    LAST_STATUS_CODE    NUMBER(3),
    FINAL_STATUS        VARCHAR2(20) DEFAULT 'PENDING',
    LAST_RETRY_TIMESTAMP TIMESTAMP,
    SOURCE_RECORD_ID    VARCHAR2(100),
    CORRELATION_ID      VARCHAR2(50),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(50),
    UPDATED_AT          TIMESTAMP,
    UPDATED_BY          VARCHAR2(50),
    CONSTRAINT FK_FAILED_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENT_CONFIGURATION(CLIENT_ID),
    CONSTRAINT CHK_FINAL_STATUS CHECK (FINAL_STATUS IN ('PENDING', 'SUCCESS', 'EXHAUSTED'))
);

CREATE INDEX IDX_FAILED_CLIENT ON FAILED_API_CALLS(CLIENT_ID);
CREATE INDEX IDX_FAILED_STATUS ON FAILED_API_CALLS(FINAL_STATUS);
CREATE INDEX IDX_FAILED_NEXT_RETRY ON FAILED_API_CALLS(NEXT_RETRY_TIME);
CREATE INDEX IDX_FAILED_CORRELATION ON FAILED_API_CALLS(CORRELATION_ID);

-- Composite index for retry processing
CREATE INDEX IDX_FAILED_STATUS_RETRY ON FAILED_API_CALLS(FINAL_STATUS, NEXT_RETRY_TIME);

COMMENT ON TABLE FAILED_API_CALLS IS 'Queue for failed API calls pending retry';
COMMENT ON COLUMN FAILED_API_CALLS.RETRY_COUNT IS 'Current retry attempt (0-360)';
COMMENT ON COLUMN FAILED_API_CALLS.MAX_RETRY_ATTEMPTS IS 'Maximum retry attempts (default 360 = 15 days)';
COMMENT ON COLUMN FAILED_API_CALLS.FINAL_STATUS IS 'PENDING=awaiting retry, SUCCESS=retry succeeded, EXHAUSTED=max retries reached';

-- ===========================================
-- Sample Source Tables (for testing)
-- These represent typical client data tables
-- ===========================================

-- Customer table (example source table)
CREATE TABLE CUSTOMER (
    ID              VARCHAR2(50) PRIMARY KEY,
    FIRST_NAME      VARCHAR2(100),
    LAST_NAME       VARCHAR2(100),
    EMAIL           VARCHAR2(255),
    PHONE           VARCHAR2(50),
    DATE_OF_BIRTH   DATE,
    CUSTOMER_TYPE   VARCHAR2(20),
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Customer Address table (example related table)
CREATE TABLE CUSTOMER_ADDRESS (
    ID              VARCHAR2(50) PRIMARY KEY,
    CUSTOMER_ID     VARCHAR2(50) NOT NULL,
    ADDRESS_TYPE    VARCHAR2(20) DEFAULT 'HOME',
    STREET_LINE_1   VARCHAR2(200),
    STREET_LINE_2   VARCHAR2(200),
    CITY            VARCHAR2(100),
    STATE           VARCHAR2(50),
    POSTAL_CODE     VARCHAR2(20),
    COUNTRY         VARCHAR2(50) DEFAULT 'USA',
    CONSTRAINT FK_ADDRESS_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(ID)
);

-- Order table (example source table)
CREATE TABLE ORDER_HEADER (
    ID              VARCHAR2(50) PRIMARY KEY,
    CUSTOMER_ID     VARCHAR2(50) NOT NULL,
    ORDER_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT    NUMBER(15,2),
    CURRENCY        VARCHAR2(3) DEFAULT 'USD',
    STATUS          VARCHAR2(20) DEFAULT 'PENDING',
    NOTES           VARCHAR2(1000),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(ID)
);

COMMENT ON TABLE CUSTOMER IS 'Sample source table for customer data';
COMMENT ON TABLE CUSTOMER_ADDRESS IS 'Sample source table for customer addresses';
COMMENT ON TABLE ORDER_HEADER IS 'Sample source table for order data';
